export type HookType =
    "useState"
    | "useReducer"
    | "useContext"
    | "useRef"
    | "useEffect"
    | "useEffectEvent"
    | "useInsertionEffect"
    | "useLayoutEffect"
    | "useCallback"
    | "useMemo"
    | "useImperativeHandle"
    | "useDebugValue"
    | "useDeferredValue"
    | "useTransition"
    | "useSyncExternalStore"
    | "useId"
    | "useCacheRefresh"
    | "useOptimistic"
    | "useFormState";
