export const
    SUSPENSE_START_DATA = "$",
    SUSPENSE_END_DATA = "/$",
    SUSPENSE_PENDING_START_DATA = "$?",
    SUSPENSE_FALLBACK_START_DATA = "$!",
    FORM_STATE_IS_MATCHING = "F!",
    FORM_STATE_IS_NOT_MATCHING = "F";
