name: Manage runners

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  manage-jobs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Job ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get-job-id
        run: |
          JOB_ID=$(gh api repos/zenflux/zenflux/actions/runs --jq '.workflow_runs[] | select(.status == "queued" and .path == ".github/workflows/0-main-self-hosted.yml") | .id' | head -1)
          echo "::set-output name=job_id::$JOB_ID"

      - name: Cancel Job
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const delay = ms => new Promise(res => setTimeout(res, ms));

            async function cancelWorkflow() {
              const jobId = "${{ steps.get-job-id.outputs.job_id }}";

              if (jobId) {
                await github.rest.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: jobId
                });

                while (true) {
                  core.info('Waiting for workflow to cancel ...');
                  await delay(5000);

                  const { status } = await github.rest.actions.getWorkflowRun({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: jobId
                  });

                  if (status !== 'in_progress') {
                    core.info('Workflow has been cancelled');
                    break;
                  }
                }
              } else {
                core.info('No queued runs to cancel');
              }
            }

            cancelWorkflow();
