name: Main workflow

on: [ push, pull_request ]

jobs:
  start-react-packages-workflow:
    uses: ./.github/workflows/react-packages.yml
    with:
      runs-on: ubuntu-latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
