name: React packages

on: [push, pull_request]

jobs:
  react-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run @z-cli @build --workspace "react-*" --haltOnDiagnosticError

      - name: Run Tests
        run: bun run @z-flux:jest:react
